### ISSUE TITLE
Client: Expire the Undo option

### ISSUE THREAD

**Issue by roughani** [code4sac/bikeandwalk#10]
_From @wleddy on January 14, 2016 17:30_

In the counters' interface page, after a trip is recoded the user has the option to "Undo" the last count. The undo option is available until they click a traveler icon to record the next trip.

I would like the Undo option to expire after say, 15 seconds so that a user won't unintentionally undo a trip.

It's my experience as a counter that you know right away if you picked the wrong traveler or lane and so you quickly delete the last count and then re-enter it correctly.

_Copied from original issue: wleddy/bikeandwalk#17_

**Comment by wleddy** [comment]
Added
