### ISSUE TITLE
Add map support to Location form

### ISSUE THREAD

**Issue by roughani** [code4sac/bikeandwalk#3]
_From @wleddy on January 1, 2016 18:11_

Add a map to the Location edit form to allow users to locate the count location, drop a pin and have the lat/long fields populate with the location of the pin.

I anticipate using open street map data for the map layer http://openstreetmap.org

See http://leafletjs.com/

_Copied from original issue: wleddy/bikeandwalk#5_

**Comment by wleddy** [comment]
Jim Ryan completed this issue
